### ISSUE TITLE
Unable to find remote helper for 'https' / CURL_OPENSSL_3 not found

### ISSUE THREAD

**Issue by AlexTugarev** [desktop/dugite#211]
After upgrading to latest dugite in Theia, we see an issue using the embedded git on Ubuntu bionic. 

I just verified this in a fresh docker container `FROM buildpack-deps:bionic`, that even the initial `git clone` from https fails because CURL_OPENSSL_3 was not found. 

```
folder# /ws/node_modules/dugite/git/libexec/git-core/git clone https://github.com/theia-ide/theia
Cloning into 'theia'...
warning: templates not found in //share/git-core/templates
fatal: Unable to find remote helper for 'https'
```

For completeness sake, I installed `git`, `nodejs`, and `npm` and added just `dugite@1.74.0` to be installed via `npm`, which installed it like this:

```
> dugite@1.74.0 postinstall /ws/node_modules/dugite
> node ./script/download-git.js

Downloading Git from: https://github.com/desktop/dugite-native/releases/download/v2.18.0-4/dugite-native-v2.18.0-ubuntu.tar.gz
```

**Comment by shiftkey** [comment]
@AlexTugarev thanks for the report!

This is an issue with how I'm building Git due to differences between flavours of Ubuntu while trying to target plain `libcurl`. I'm tracking this in the native package itself, but not quite sure how to address it currently: https://github.com/desktop/dugite-native/issues/109
