### ISSUE TITLE
How to login with username and accessToken?

### ISSUE THREAD

**Issue by linonetwo** [desktop/dugite#410]
I'm trying to push

```js
  const options = {
    env: {
      GITHUB_TOKEN,
    },
  };
  const { stderr: pushStdError, exitCode: pushExitCode } = await GitProcess.exec(
    ['push', 'origin', 'master', '--force'],
    repoPath,
    options,
  );
```

but this always comes with 

```
git: 'credential-osxkeychain' is not a git command. See 'git --help'.
remote: No anonymous write access.
fatal: Authentication failed for 'https://github.com/tiddlygit-test/wikitest.git/'
```

I think this is caused by my no passing a username to it, but how to pass in a username? I don't want to use the global username config, I'd like to set it at runtime.

**Comment by linonetwo** [comment]
And when I start my app in VSCode's terminal, I always got this prompt:

![Screen Shot 2020-07-18 at 2 58 17 PM](https://user-images.githubusercontent.com/3746270/87847012-1e634e00-c907-11ea-80c0-7bfd5d1726f7.png)

(extension "GitHub" wants to use Github signin)

**Comment by linonetwo** [comment]
I don't know how Github Desktop handles this, but this works for me in my electron app:

```js
  const { login: username, email, accessToken } = userInfo;
  const gitUrl = `${githubRepoUrl}.git`.replace(
    'https://github.com/',
    `https://${username}:${accessToken}@github.com/`,
  );
```

where `userInfo` comes from the OAuth app.

**Comment by rafeca** [comment]
Hey @linonetwo! 

In GitHub Deskop we use the `GIT_ASKPASS` env variable to tell `git` to execute one of our binaries to get the credentials.

How this works is in the following way:

1. We pass the `-c credential.helper=` CLI argument to any `git` command ([source](https://github.com/desktop/desktop/blob/cd4cc7891f610ff378bc656540ac983e27fe3262/app/src/lib/git/core.ts#L406-L411)) that uses the network to make sure that no user-provided auth mechanism is used (to rely only on our own implementation).
2. We set the `GIT_ASKPASS` env variable to point to our executable file that provides the user/password to git ([source](https://github.com/desktop/desktop/blob/development/app/src/lib/git/authentication.ts#L11)).
3. `git` will then call this executable twice, one time to get the username and a second time to get the password. We have some simple logic to be able to provide both things using the same executable ([source](https://github.com/desktop/desktop/blob/development/app/src/ask-pass/ask-pass.ts#L13-L23)).

The most tricky part of this process is to manage the env variables: since there's no connection between the Desktop process and the `GIT_ASKPASS` process we need to pass some information via env variables (like the username). Luckily we get the password directly from the `GIT_ASKPASS` process by asking it to the OS keychain so we avoid passing passwords around.

Another option is to create our own git credentials helpers ([see the official git docs](https://git-scm.com/docs/gitcredentials)), but the overall architecture of the solution would have been very similar anyways.

The solution you pointed in https://github.com/desktop/dugite/issues/410#issuecomment-660446227 may work fine in your case where you have an access token, so if you just need to support pushing to GitHub and always have access tokens that's going to be much simpler than the Desktop implementation.

The more complex `GIT_ASKPASS` approach will just be a more generic solution that works for any git provider and supports user/password authentication.

Hope this helps!

**Comment by linonetwo** [comment]
Hi Rafeca, Thank you for such a detailed explanation! I got it.

**Comment by zhoushaokun** [comment]
Thank you for such a detailed explanation! But I want to go deeper,
As for

> 1. We pass the -c credential.helper= CLI argument to any git command ([source](https://github.com/desktop/desktop/blob/cd4cc7891f610ff378bc656540ac983e27fe3262/app/src/lib/git/core.ts#L406-L411)) that uses the network to make sure that no user-provided auth mechanism is used (to rely only on our own implementation).
> 2. We set the GIT_ASKPASS env variable to point to our executable file that provides the user/password to git ([source](https://github.com/desktop/desktop/blob/development/app/src/lib/git/authentication.ts#L11)).

Is it related to the mechanism of [git credentials/REQUESTING CREDENTIALS](https://git-scm.com/docs/gitcredentials#_requesting_credentials) ?

Thanks for your reply!
