### ISSUE TITLE
Return process or PID in IGitResult

### ISSUE THREAD

**Issue by maifeeulasad** [desktop/dugite#443]
in [IGitResult](https://github.com/desktop/dugite/blob/85a76d38ce85a3e9fffa1fabd4cfc6a995695b4c/lib/git-process.ts#L15), process or PID can be returned so that, it will help many other operations.

Like : 
 - [canceling](https://github.com/desktop/desktop/issues/2082#event-4630789769)

**Comment by maifeeulasad** [comment]
And if this is getting implemented, can I get assigned to this?

**Comment by sergiou87** [comment]
Hey @maifeeulasad! 👋 

Thank you for your suggestion. However, I think that wouldn't be very useful because `IGitResult` represents the result of the `git` process **once it's finished**. At that point, the PID is not valid because the process doesn't exist anymore 😓 

You would need to return the PID **along with the `Promise<IGitResult>`**, but that wouldn't end in a very clean API, in my opinion 😞

**Comment by maifeeulasad** [comment]
@sergiou87 can we pass an additional optional callback function, like this and that will return us the PID ?
```
public static exec(args: string[], path: string, options?: IGitExecutionOptions,pidCallback?: (pid: number) => void): Promise<IGitResult>;
```
Then we have the pid, check if it is undefined or not, if not, then we can use it to kill or other purposes.
This is what I thought of till now.

**Comment by sergiou87** [comment]
I'm not particularly convinced about that specific approach, to be honest, it feels a bit hacky to me 😳 

I think this would require a bigger API change:
- Create a new abstraction called, let's say, `GitTask`, which represents a git process.
- This abstraction would have:
	- An **internal private** property storing the PID of the git process (or something equivalent).
	- A `result: Promise<IGitResult>` property to obtain the result of the process.
	- A method like `cancel()` to kill the process while it's running. I imagine the implementation of this method would kill the process using its PID and somehow signal that the process was cancelled.
- `exec` would return a `GitTask` instance instead of `Promise<IGitResult>`.

With that change, code that now looks like this:
```typescript
const result = await exec(…)
```

Would look like this:
```typescript
const task = exec(…)
const result = await task.result
```

And you can invoke `task.cancel()` to kill it at any time. That means `IGitResult` might need an additional field to indicate when the process was cancelled.

Does that make sense? 😳   I'm open to feedback and other suggestions about this 😄  My main concern is that this breaks the current API… but maybe we can create a new `execTask` function that returns this `GitTask`, and then implement the existing `exec` like this:
```typescript
public static exec(args: string[], path: string, options?: IGitExecutionOptions,pidCallback?: (pid: number) => void): Promise<IGitResult> {
  const task = execTask(…)
  return task.result
}
```

@tidy-dev What do you think?

**Comment by tidy-dev** [comment]
@sergiou87 All makes sense to me and like the bit about making an execTask to reduce implementation impact.

**Comment by maifeeulasad** [comment]
@sergiou87 damn, this is so cool
can I take part in the implementation?

**Comment by sergiou87** [comment]
Absolutely @maifeeulasad! ❤️ 

Please, consider adding some tests around that new `cancel` method to make sure it works as expected before we attempt to use it in GitHub Desktop 😄 

Thank you for your work!
