### ISSUE TITLE
Stream Commands to GitProcess

### ISSUE THREAD

**Issue by captainrdubb** [desktop/dugite#459]
Is it possible to stream commands to GitProcess, then close the underlying child_process when I'm done?

**Comment by sergiou87** [comment]
Hey @captainrdubb! 👋 

What do you have in mind exactly? Something like running multiple `git` commands in just one process?

If that's it, I don't think `git` supports that: you must spawn a new `git` process for every command. AFAIK, `git` subcommands are written in a way they don't free resources cleanly after doing their work, since they assume the whole git process will end and the OS will take back all the resources used by git anyway. Therefore, running multiple `git` subcommands in the same process would be a bit messy.

 Does that answer your question? 😳

**Comment by captainrdubb** [comment]
@sergiou87 i think it does. i haven't fully grasped how node child processes work. my understanding is that there's Node land and system land. A child process is something that exists in Node land and sends commands to things in system land, like git. i was wondering if a Node child process could stay alive in Node land and that I could continually push commands to that child process which would subsequently execute commands against other executables, scripts, etc. that exist in system land.

**Comment by niik** [comment]
> Ultimately, I want to avoid creating child processes for each command.

I'm afraid that's the only way to do it. Git in particular is not built for re-use and will exit at first sign of trouble and is intentionally lax with memory management given how short-lived its processes are. The good news is that the overhead on Node's side isn't significant. Spawning processes on Windows can be costly but that cost is not the fault of child_process. GitHub Desktop spawns countless Git processes in rapid succession as part of its normal operation.

Given this I'm going to close this issue, thanks for reaching out!
