### ISSUE TITLE
Easier cross platform building

### ISSUE THREAD

**Issue by rlabrecque** [desktop/dugite#95]
I'm doing some cross compilation stuff for GHD and the usage of process.platform at build time in https://github.com/desktop/dugite/blob/master/script/config.js isn't great for that.

JS/Node isn't my usual cup of tea so I might be doing something dumb here but this works! On GHD I just replaced all instances of process.platform with this:

```
function getTargetPlatform () {
  const platform = process.env.TARGET_PLATFORM || process.platform
  if(platform != 'darwin' && platform != 'win32') {
    console.error(`Exiting - I'm not set up to work on ${platform} yet! :(`)
    process.exit(1)
  }

  return platform
}
```

Which lets me build like: `TARGET_PLATFORM=win32 npm run build:dev`

Could we do something like that here as well or is there a better way to override process.platform?

**Comment by shiftkey** [comment]
So I don't think this is a great change because of how `npm install` works - this config file gets invoked as part of `npm install` to grab the appropriate package you need to invoke Git **for your current OS**. Not only does this affect the developer-time experience of contributors, it also affects how users who want to install `dugite` will get started.

And `npm run build` itself doesn't have any sort of dependency on the current platform, so I'm not sure what changes in `dugite` we can make to improve this issue: https://github.com/desktop/dugite/blob/094578636530405f12bbf53cae1f899e818bad06/package.json#L10

**Comment by rlabrecque** [comment]
Yeah, not really worth it with https://github.com/desktop/desktop/issues/1681 closed anyway, so don't worry about it :)
