### ISSUE TITLE
Dugite vs. Nodegit

### ISSUE THREAD

**Issue by svenefftinge** [desktop/dugite#98]
Dugite seems to be similar to Nodegit (https://github.com/nodegit/nodegit) in that it provides an API to interact with git.
Could you explain the differences and/or why you decided to work on dugite?

**Comment by svenefftinge** [comment]
I was pointed to https://githubengineering.com/integrating-git-in-atom/ which answers my question. Thanks!

**Comment by shiftkey** [comment]
@svenefftinge yeah, that's a good introduction to the two approaches.

Some other notes:

 - `nodegit` doesn't support the full set of Git commands, arguments and formatting that Git core does. Because `dugite` packages core Git we can use all the options available that a CLI user might need. This lets us do [neat things](https://github.com/desktop/desktop/blob/87041dadbaf690a9ab1c9d22bd37ba37c0beb34d/app/src/lib/git/reflog.ts#L10) without having to submit PRs upstream for every little thing
 - we had some ongoing issues with subtle behaviour changes between `libgit2` (which `nodegit` builds upon) and Git core that lead to support issues which remain unresolved.
 - by invoking Git out-of-process with `dugite` we avoid the memory footprint affecting the current process, and releasing memory becomes as simple as tearing down the process - which operating systems are great at.

There's also some great discussion about the tradeoffs from months ago here https://github.com/atom/github/pull/524#issuecomment-280747959 and here https://github.com/atom/github/pull/524#issuecomment-280961626 - the Desktop team wanted to focus on the correctness of the Git operations, and our past experiences pointed us to moving away from `nodegit` to using Git core.
